In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

In [19]:
df = pd.read_csv('academicos_historico_balanceado.csv')
df.head()

chave  idade  corRaca  trancamentos  \
0  899F5044-7AD1-4CCE-88B1-38A1C6B0A0C4   24.0        0             0   
1  17A24172-777E-46D9-BFDF-D9465B1DCE4D   33.0        1             0   
2  BCB43225-578A-48EC-99DA-E242A4DF0B64   24.0        0             2   
3  DB643205-09FF-4E5A-8E24-0B8E4E7FF4C2   38.0        1             1   
4  C4E050D5-0EAD-4686-8806-F703B41C8439   25.0        1             0   

   notaIngresso  escolaPublica      nota      falta  ultimoSemestre  \
0        657.30              0  3.150130  20.597403             8.0   
1        543.40              0  7.463425   2.849315             9.0   
2        575.66              0  3.061905  16.619048             1.0   
3        521.84              0  6.229167  13.555556             4.0   
4        657.30              1  7.877632   2.552632             8.0   

   quantidadeRematricula  ...  estadoCivil_code  deficiencia_code  matutino  \
0                     12  ...                 0                 0         1   
1                     11  ...                 0                 0         1   
2                      4  ...                 0                 0         1   
3                      4  ...                 0                 0         0   
4                      8  ...                 0                 0         1   

   vespertino  noturno  tipoVaga_code  moraCampus  grande_area  \
0           1        0              0           0            5   
1           1        0              0           1            5   
2           1        0              0           1            5   
3           0        1              1           0            5   
4           1        0              0           0            4   

   tempo_2_grau_superior  evadido  
0                      2        1  
1                      0        0  
2                      2        1  
3                      6        1  
4                      2        0  

[5 rows x 27 columns]

In [20]:
colunas = df.columns
lista_colunas = list(df.columns)
lista_colunas.remove('chave')
lista_colunas.remove('evadido')
x = df[lista_colunas]
y = df['evadido']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=18)

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
randomdorest = RandomForestClassifier(n_estimators=100)

randomdorest.fit(X_train,y_train)

RandomForestClassifier()

In [24]:
print('Dados de treinamento')

predicao = randomdorest.predict(X_train)

print(confusion_matrix(y_train,predicao))
print(classification_report(y_train,predicao))

Dados de treinamento
[[8612    0]
 [   0 8639]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      8612
           1       1.00      1.00      1.00      8639

    accuracy                           1.00     17251
   macro avg       1.00      1.00      1.00     17251
weighted avg       1.00      1.00      1.00     17251



In [25]:
print('Dados de teste')

predicao = randomdorest.predict(X_test)

print(confusion_matrix(y_test,predicao))
print(classification_report(y_test,predicao))

Dados de teste
[[1855  315]
 [ 128 2015]]
              precision    recall  f1-score   support

           0       0.94      0.85      0.89      2170
           1       0.86      0.94      0.90      2143

    accuracy                           0.90      4313
   macro avg       0.90      0.90      0.90      4313
weighted avg       0.90      0.90      0.90      4313



In [26]:
importances = randomdorest.feature_importances_
for i, v in enumerate(importances):
    print(f'Feature: {i}, Score: {v}')

Feature: 0, Score: 0.04187576170682042
Feature: 1, Score: 0.007831697851051546
Feature: 2, Score: 0.14906111425247387
Feature: 3, Score: 0.042701941712178365
Feature: 4, Score: 0.007083399901006344
Feature: 5, Score: 0.10000986878143996
Feature: 6, Score: 0.07755903070425096
Feature: 7, Score: 0.047316850109080176
Feature: 8, Score: 0.05975776240053209
Feature: 9, Score: 0.02475486416715597
Feature: 10, Score: 0.05581097003970599
Feature: 11, Score: 0.169696855740335
Feature: 12, Score: 0.06854282880290692
Feature: 13, Score: 0.041030304386921006
Feature: 14, Score: 0.026663053028436513
Feature: 15, Score: 0.0060644796460172365
Feature: 16, Score: 0.001878937512708062
Feature: 17, Score: 0.0009204895828717638
Feature: 18, Score: 0.0053626116180462615
Feature: 19, Score: 0.0062505050589148035
Feature: 20, Score: 0.004879740790107849
Feature: 21, Score: 0.007121819705144194
Feature: 22, Score: 0.003214508128818582
Feature: 23, Score: 0.02078453872593471
Feature: 24, Score: 0.023826065647

In [27]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_estimators': [100, 200, 300],  # Número de árvores
    'max_depth': [None, 10, 20, 30],  # Profundidade máxima
    'min_samples_split': [2, 5, 10],  # Mínimo de amostras para dividir um nó
    'min_samples_leaf': [1, 2, 4],    # Mínimo de amostras em uma folha
    'bootstrap': [True, False]        # Usar ou não amostragem com reposição
}

# Criar o GridSearchCV
grid_search = GridSearchCV(estimator=randomdorest, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2, scoring='accuracy')

In [28]:
import time
inicio = time.time()  # Tempo inicial

In [29]:
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 216 candidates, totalling 648 fits


c:\Users\bsabd\anaconda3\Lib\site-packages\numpy\ma\core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'max_depth': [None, 10, 20, 30],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='accuracy', verbose=2)

In [30]:
fim = time.time()  # Tempo final
tempo_execucao = fim - inicio

print(f"Tempo de execução: {tempo_execucao} segundos")

Tempo de execução: 232.64468002319336 segundos


In [31]:
# Melhor combinação de hiperparâmetros
print(f'Melhores parâmetros: {grid_search.best_params_}')

# Melhor modelo após ajuste de hiperparâmetros
best_model = grid_search.best_estimator_

Melhores parâmetros: {'bootstrap': False, 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 300}


In [32]:
print('Dados de treinamento')

predicao = randomdorest.predict(X_train)

print(confusion_matrix(y_train,predicao))
print(classification_report(y_train,predicao))

Dados de treinamento
[[8612    0]
 [   0 8639]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      8612
           1       1.00      1.00      1.00      8639

    accuracy                           1.00     17251
   macro avg       1.00      1.00      1.00     17251
weighted avg       1.00      1.00      1.00     17251



In [33]:
print('Dados de teste')

inicio = time.time()

predicao = randomdorest.predict(X_test)

fim = time.time()  # Tempo final
tempo_execucao = fim - inicio

print(f"Tempo de execução: {tempo_execucao} segundos")

print(confusion_matrix(y_test,predicao))
print(classification_report(y_test,predicao))

Dados de teste
Tempo de execução: 0.05706334114074707 segundos
[[1855  315]
 [ 128 2015]]
              precision    recall  f1-score   support

           0       0.94      0.85      0.89      2170
           1       0.86      0.94      0.90      2143

    accuracy                           0.90      4313
   macro avg       0.90      0.90      0.90      4313
weighted avg       0.90      0.90      0.90      4313

